---
- name: Run
  hosts: all

  tasks:
  - name: Remove all previuos instances MicroK8S
    include_role: 
      name: remove_microk8s
    when: remove | default(False)

  - name: Install MicroK8S
    include_role: 
      name: install_microk8s
    when: install | default(False)

  - name: Apply
    import_tasks: tasks/apply.yml
    when: apply | default(False)

  - name: Delete
    import_tasks: tasks/delete.yml
    when: delete | default(False)