---
- name: Run
  hosts: all

  tasks:
  - name: Remove all previuos instances MicroK8S
    include_role: 
      name: remove_microk8s
    when: remove | default(False)

  - name: Install MicroK8S
    include_role: 
      name: install_microk8s
    when: install | default(False)

  ### MicroServices KS8 ### APPLY

  - name: Copy file
    import_tasks: tasks/copy_manifest_to_server.yml
    when: apply | default(False)
  
  - name: Kubectl command
    import_tasks: tasks/kubectl_apply.yml
    when: apply | default(False)

  - name: Delete file
    import_tasks: tasks/delete_manifest_from_server.yml
    when: apply | default(False)

  ### MicroServices K8S ### DELETE

  - name: Copy file
    import_tasks: tasks/copy_manifest_to_server.yml
    when: delete | default(False)

  - name: Kubectl command
    import_tasks: tasks/kubectl_delete.yml
    when: delete | default(False)

  - name: Delete file
    import_tasks: tasks/delete_manifest_from_server.yml
    when: delete | default(False)