---
- name: microk8s group
  user:
    name: '{{ lookup("env", "USER") }}'
    state: present
    groups:
      - microk8s
    append: true
  become: true
  vars:
    ansible_become_password: "{{ ansible_ssh_pass }}"