---
- name: Remove .kube folder for the user
  become: true
  become_user: '{{ user }}'
  file:
    path: "/home/{{ users }}/.kube"
    state: absent
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: Remove .kube folder for ansible-core
  delegate_to: localhost
  file:
    path: "{{ export_config_kubectl_dest }}"
    state: absent
  when: export_config_kubectl