- name: Reboot hosts
  shell: reboot
  async: 1
  poll: 0
  become: true

- name: Waiting host again up
  wait_for_connection:
    timeout: 300

- name: Notification host ready up
  debug:
    msg: "El servidor está en línea."