---
- name: add helm repository to user
  become: true
  become_user: '{{ item.0 }}'
  shell: "microk8s helm repo add {{ item.1.name }} {{ item.1.url }}"
  args:
    executable: /bin/bash
  changed_when: true
  with_nested:
    - "{{ users }}"
    - "{{ helm3_repositories }}"
  when: microk8s_plugins.helm3

- name: update helm repos
  become: true
  become_user: '{{ user }}'
  shell: "microk8s helm repo update"
  args:
    executable: /bin/bash
  changed_when: true
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugins.helm3
