---
- name: Install microk8s
  snap:
    name:
      - microk8s
    state: present
    classic: yes
    #channel: "{{ microk8s_version }}"
  become: true

- name: Wait for microk8s to be ready
  become: true
  command: microk8s.status --wait-ready
  changed_when: false
  register: mk8sstatusout
  failed_when:
      - "'This MicroK8s deployment is acting as a node in a cluster.' not in mk8sstatusout.stdout_lines"
      - mk8sstatusout.rc > 0
